name: Release Android

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release, 0.5.1 (without 'v')"
        required: true

jobs:
  android:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.3.10"
      ANDROID_CODE_SIGN_ENABLED: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.API_GITHUB_TOKEN }}
          # default is '', i.e. commit that triggered this event
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version != '' && format('refs/tags/v{0}', github.event.inputs.version) || ''}}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{env.JAVA_VERSION}}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}

      - name: Deps
        run: flutter pub get
      
      - name: Setup version and tag
        id: setup
        env:
          VERSION_CODE: ${{ github.run_number }}
        run: |
          if [ ${{ github.event_name }} != 'workflow_dispatch' ]; then
            echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
            echo "version=${GITHUB_REF##*/v}" >> $GITHUB_OUTPUT
          else
            echo "tag=v${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi
          echo "version_code=$(($VERSION_CODE+42))" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set Version
        run: sed -i 's/1337.42.1337+42/${{ steps.setup.outputs.version }}+${{ steps.setup.outputs.version_code }}/g' pubspec.yaml
      
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2.3
        with:
          fileName: keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties

      - name: Build
        run: |
          flutter build apk --release
          flutter build appbundle --release
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/WiiMoteDSU-${{ steps.setup.outputs.tag }}.apk
          mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/WiiMoteDSU-${{ steps.setup.outputs.tag }}.aab

      - name: Upload assets
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'build/app/outputs/flutter-apk/WiiMoteDSU-${{ steps.setup.outputs.tag }}.apk;build/app/outputs/bundle/release/WiiMoteDSU-${{ steps.setup.outputs.tag }}.aab'
          release-tag: ${{ steps.setup.outputs.tag }}
          repo-token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Release app to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          packageName: nl.dijkitech.wiimote_dsu
          releaseFiles: build/app/outputs/bundle/release/WiiMoteDSU-${{ steps.setup.outputs.tag }}.aab
          track: production
          status: completed
