name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Setup environment
        id: setup
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth=1
          flutter/bin/flutter doctor
          echo ::set-output name=tag::${GITHUB_REF##*/}

      - name: Build
        run: |
          flutter/bin/flutter build ios --no-codesign --release
          cd build/ios/
          mv iphoneos Payload
          zip -r WiiMoteDSU-${{ steps.setup.outputs.tag }}.ipa Payload

      - name: Upload assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: build/ios/WiiMoteDSU-${{ steps.setup.outputs.tag }}.ipa
          release-tag: ${{ steps.setup.outputs.tag }}
          repo-token: ${{ secrets.API_GITHUB_TOKEN }}

  android:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.3.10"
      ANDROID_CODE_SIGN_ENABLED: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{env.JAVA_VERSION}}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}

      - name: Deps
        id: setup
        run: |
          flutter pub get
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF##*/v}" >> $GITHUB_OUTPUT

      - name: Set Version
        run: sed -i 's/1337.42.1337+42/${{ steps.setup.outputs.version }}+${{ github.run_number }}/g' pubspec.yaml
      
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: android/upload-keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties

      - name: Build
        run: |
          flutter build apk --release
          flutter build appbundle --release
          cd build/app/outputs/flutter-apk/
          mv app-release.apk WiiMoteDSU-${{ steps.setup.outputs.tag }}.apk
          cd ../release/app-release.aab
          mv app-release.aab WiiMoteDSU-${{ steps.setup.outputs.tag }}.aab

      - name: Upload assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/app/outputs/flutter-apk/WiiMoteDSU-${{ steps.setup.outputs.tag }}.apk;build/app/outputs/release/WiiMoteDSU-${{ steps.setup.outputs.tag }}.aab'
          release-tag: ${{ steps.setup.outputs.tag }}
          repo-token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Release app to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          packageName: nl.dijkitech.DSU_Remote
          releaseFiles: build/app/outputs/release/WiiMoteDSU-${{ steps.setup.outputs.tag }}.aab
          track: production
          status: inProgress
